//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infra.Exceptions.TextosErros {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Erros {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Erros() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infra.Exceptions.TextosErros.Erros", typeof(Erros).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentes da ordem não podem ser menor de idade..
        /// </summary>
        public static string AgenteMenorDeIdade {
            get {
                return ResourceManager.GetString("AgenteMenorDeIdade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A idade máxima de um agente da ordem é 80 anos..
        /// </summary>
        public static string AgentesComMaisDe80Anos {
            get {
                return ResourceManager.GetString("AgentesComMaisDe80Anos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O máximo de NEX que uma pessoa pode ter é 99..
        /// </summary>
        public static string NEXDoAgenteMaiorQue99 {
            get {
                return ResourceManager.GetString("NEXDoAgenteMaiorQue99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O NEX não pode ser negativo.
        /// </summary>
        public static string NEXDoAgenteNegativo {
            get {
                return ResourceManager.GetString("NEXDoAgenteNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agentes da ordem podem ter no máximo 10 níveis..
        /// </summary>
        public static string NivelDoAgenteMaiorQue10 {
            get {
                return ResourceManager.GetString("NivelDoAgenteMaiorQue10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nível não pode ser negativo..
        /// </summary>
        public static string NivelDoAgenteNegativo {
            get {
                return ResourceManager.GetString("NivelDoAgenteNegativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O personagem não foi encontrado na base de dados..
        /// </summary>
        public static string PersonagemNaoEncontrado {
            get {
                return ResourceManager.GetString("PersonagemNaoEncontrado", resourceCulture);
            }
        }
    }
}
